from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `candlewood` DROP FOREIGN KEY `fk_candlewo_stock_e0b7b11b`;
        ALTER TABLE `candletransportequip` DROP FOREIGN KEY `fk_candletr_stock_210f970a`;
        ALTER TABLE `candletransportdepot` DROP FOREIGN KEY `fk_candletr_stock_d33969e6`;
        ALTER TABLE `candletelecommunication` DROP FOREIGN KEY `fk_candlete_stock_11158675`;
        ALTER TABLE `candlestockindustry` DROP FOREIGN KEY `fk_candlest_stock_f3a5b062`;
        ALTER TABLE `candlesteel` DROP FOREIGN KEY `fk_candlest_stock_45074222`;
        ALTER TABLE `candleservice` DROP FOREIGN KEY `fk_candlese_stock_a1e68575`;
        ALTER TABLE `candlenonmetal` DROP FOREIGN KEY `fk_candleno_stock_8d21634d`;
        ALTER TABLE `candlemedication` DROP FOREIGN KEY `fk_candleme_stock_1051af1a`;
        ALTER TABLE `candlemedicalprecision` DROP FOREIGN KEY `fk_candleme_stock_7db38f8c`;
        ALTER TABLE `candlemechanic` DROP FOREIGN KEY `fk_candleme_stock_48933df1`;
        ALTER TABLE `candlemanufacturing` DROP FOREIGN KEY `fk_candlema_stock_e508eb82`;
        ALTER TABLE `candleinsurance` DROP FOREIGN KEY `fk_candlein_stock_aa9ab4ee`;
        ALTER TABLE `candlefood` DROP FOREIGN KEY `fk_candlefo_stock_7a5a724a`;
        ALTER TABLE `candlefinance` DROP FOREIGN KEY `fk_candlefi_stock_23d35b23`;
        ALTER TABLE `candlefiber` DROP FOREIGN KEY `fk_candlefi_stock_2f21b049`;
        ALTER TABLE `candleelectronic` DROP FOREIGN KEY `fk_candleel_stock_c0556966`;
        ALTER TABLE `candleelecgas` DROP FOREIGN KEY `fk_candleel_stock_ec339693`;
        ALTER TABLE `candledistribution` DROP FOREIGN KEY `fk_candledi_stock_501160d9`;
        ALTER TABLE `candleconstruction` DROP FOREIGN KEY `fk_candleco_stock_9754b5a9`;
        ALTER TABLE `candlechemistry` DROP FOREIGN KEY `fk_candlech_stock_fb7ffa81`;
        ALTER TABLE `candlebank` DROP FOREIGN KEY `fk_candleba_stock_b98dfc39`;
        ALTER TABLE `candleagriculture` DROP FOREIGN KEY `fk_candleag_stock_36e46d3f`;
        ALTER TABLE `daywood` DROP FOREIGN KEY `fk_daywood_stock_8d0f9118`;
        ALTER TABLE `daytransportequip` DROP FOREIGN KEY `fk_daytrans_stock_eeada6d9`;
        ALTER TABLE `daytransportdepot` DROP FOREIGN KEY `fk_daytrans_stock_14c727fa`;
        ALTER TABLE `daytelecommunication` DROP FOREIGN KEY `fk_daytelec_stock_e633aff5`;
        ALTER TABLE `daystockindustry` DROP FOREIGN KEY `fk_daystock_stock_32421c39`;
        ALTER TABLE `daysteel` DROP FOREIGN KEY `fk_daysteel_stock_7bd33878`;
        ALTER TABLE `dayservice` DROP FOREIGN KEY `fk_dayservi_stock_56088eb4`;
        ALTER TABLE `daynonmetal` DROP FOREIGN KEY `fk_daynonme_stock_4968b990`;
        ALTER TABLE `daymedication` DROP FOREIGN KEY `fk_daymedic_stock_3c1751a7`;
        ALTER TABLE `daymedicalprecision` DROP FOREIGN KEY `fk_daymedic_stock_c2fd76dc`;
        ALTER TABLE `daymechanic` DROP FOREIGN KEY `fk_daymecha_stock_ece1dd8c`;
        ALTER TABLE `daymanufacturing` DROP FOREIGN KEY `fk_daymanuf_stock_7458ffdc`;
        ALTER TABLE `dayinsurance` DROP FOREIGN KEY `fk_dayinsur_stock_d2c2c8d7`;
        ALTER TABLE `dayfood` DROP FOREIGN KEY `fk_dayfood_stock_2e44b0e3`;
        ALTER TABLE `dayfinance` DROP FOREIGN KEY `fk_dayfinan_stock_1a9b39b4`;
        ALTER TABLE `dayfiber` DROP FOREIGN KEY `fk_dayfiber_stock_874d5549`;
        ALTER TABLE `dayelectronic` DROP FOREIGN KEY `fk_dayelect_stock_f9e38102`;
        ALTER TABLE `dayelecgas` DROP FOREIGN KEY `fk_dayelecg_stock_b6c99500`;
        ALTER TABLE `daydistribution` DROP FOREIGN KEY `fk_daydistr_stock_d1e23d88`;
        ALTER TABLE `dayconstruction` DROP FOREIGN KEY `fk_dayconst_stock_b5bb35af`;
        ALTER TABLE `daychemistry` DROP FOREIGN KEY `fk_daychemi_stock_a4dfa947`;
        ALTER TABLE `daybank` DROP FOREIGN KEY `fk_daybank_stock_c40d00ec`;
        ALTER TABLE `dayagriculture` DROP FOREIGN KEY `fk_dayagric_stock_1e97df6d`;
        ALTER TABLE `keyword` DROP FOREIGN KEY `fk_keyword_stock_2dc8f0fe`;
        ALTER TABLE `day` DROP FOREIGN KEY `fk_day_stock_24f485b8`;
        ALTER TABLE `candle` DROP FOREIGN KEY `fk_candle_stock_cc0b126d`;
        ALTER TABLE `bidask` DROP FOREIGN KEY `fk_bidask_stock_acdf070b`;
        ALTER TABLE `bidask` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candle` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `day` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `keyword` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayagriculture` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daybank` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daychemistry` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayconstruction` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daydistribution` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayelecgas` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayelectronic` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayfiber` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayfinance` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayfood` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayinsurance` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daymanufacturing` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daymechanic` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daymedicalprecision` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daymedication` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daynonmetal` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `dayservice` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daysteel` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daystockindustry` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daytelecommunication` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daytransportdepot` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daytransportequip` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `daywood` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleagriculture` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlebank` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlechemistry` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleconstruction` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candledistribution` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleelecgas` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleelectronic` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlefiber` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlefinance` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlefood` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleinsurance` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlemanufacturing` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlemechanic` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlemedicalprecision` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlemedication` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlenonmetal` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candleservice` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlesteel` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlestockindustry` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candletelecommunication` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candletransportdepot` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candletransportequip` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `candlewood` RENAME COLUMN `stock_id_id` TO `stock_id`;
        ALTER TABLE `bidask` ADD CONSTRAINT `fk_bidask_stock_7d55ead2` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candle` ADD CONSTRAINT `fk_candle_stock_7013df5a` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `day` ADD CONSTRAINT `fk_day_stock_b8a3096c` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `keyword` ADD CONSTRAINT `fk_keyword_stock_971fe9fc` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayagriculture` ADD CONSTRAINT `fk_dayagric_stock_16badcd0` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daybank` ADD CONSTRAINT `fk_daybank_stock_380418d2` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daychemistry` ADD CONSTRAINT `fk_daychemi_stock_93518ce7` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayconstruction` ADD CONSTRAINT `fk_dayconst_stock_c1ba0548` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daydistribution` ADD CONSTRAINT `fk_daydistr_stock_e5a80b4d` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayelecgas` ADD CONSTRAINT `fk_dayelecg_stock_a39fe741` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayelectronic` ADD CONSTRAINT `fk_dayelect_stock_15bbce74` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfiber` ADD CONSTRAINT `fk_dayfiber_stock_87d3bdc1` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfinance` ADD CONSTRAINT `fk_dayfinan_stock_3f442b61` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfood` ADD CONSTRAINT `fk_dayfood_stock_2c7c8e0e` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayinsurance` ADD CONSTRAINT `fk_dayinsur_stock_d73c97cd` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymanufacturing` ADD CONSTRAINT `fk_daymanuf_stock_44bf8ab5` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymechanic` ADD CONSTRAINT `fk_daymecha_stock_29c92e9e` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymedicalprecision` ADD CONSTRAINT `fk_daymedic_stock_d25d4ce0` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymedication` ADD CONSTRAINT `fk_daymedic_stock_3993e2c1` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daynonmetal` ADD CONSTRAINT `fk_daynonme_stock_f38c012f` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayservice` ADD CONSTRAINT `fk_dayservi_stock_fe57b0b7` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daysteel` ADD CONSTRAINT `fk_daysteel_stock_5104b545` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daystockindustry` ADD CONSTRAINT `fk_daystock_stock_53290646` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytelecommunication` ADD CONSTRAINT `fk_daytelec_stock_649cd6b6` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytransportdepot` ADD CONSTRAINT `fk_daytrans_stock_c3d3ce3f` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytransportequip` ADD CONSTRAINT `fk_daytrans_stock_6abbfb86` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daywood` ADD CONSTRAINT `fk_daywood_stock_cc7dcb08` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleagriculture` ADD CONSTRAINT `fk_candleag_stock_9242b727` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlebank` ADD CONSTRAINT `fk_candleba_stock_a135f1ef` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlechemistry` ADD CONSTRAINT `fk_candlech_stock_2105e37b` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleconstruction` ADD CONSTRAINT `fk_candleco_stock_261c1847` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candledistribution` ADD CONSTRAINT `fk_candledi_stock_dd3cfb17` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleelecgas` ADD CONSTRAINT `fk_candleel_stock_cefb0964` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleelectronic` ADD CONSTRAINT `fk_candleel_stock_d84727ef` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefiber` ADD CONSTRAINT `fk_candlefi_stock_1bd36ef7` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefinance` ADD CONSTRAINT `fk_candlefi_stock_7bc3f306` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefood` ADD CONSTRAINT `fk_candlefo_stock_298943d5` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleinsurance` ADD CONSTRAINT `fk_candlein_stock_aa22c97d` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemanufacturing` ADD CONSTRAINT `fk_candlema_stock_cebe2215` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemechanic` ADD CONSTRAINT `fk_candleme_stock_ef0530eb` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemedicalprecision` ADD CONSTRAINT `fk_candleme_stock_b2b2af9a` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemedication` ADD CONSTRAINT `fk_candleme_stock_6712d14b` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlenonmetal` ADD CONSTRAINT `fk_candleno_stock_347bcf6a` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleservice` ADD CONSTRAINT `fk_candlese_stock_f4567335` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlesteel` ADD CONSTRAINT `fk_candlest_stock_0e497b2a` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlestockindustry` ADD CONSTRAINT `fk_candlest_stock_0057f2d9` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletelecommunication` ADD CONSTRAINT `fk_candlete_stock_01b6f4bf` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletransportdepot` ADD CONSTRAINT `fk_candletr_stock_bc9a81c5` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletransportequip` ADD CONSTRAINT `fk_candletr_stock_638921eb` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlewood` ADD CONSTRAINT `fk_candlewo_stock_aa47ca4e` FOREIGN KEY (`stock_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `candletelecommunication` DROP FOREIGN KEY `fk_candlete_stock_01b6f4bf`;
        ALTER TABLE `candlemedicalprecision` DROP FOREIGN KEY `fk_candleme_stock_b2b2af9a`;
        ALTER TABLE `daytelecommunication` DROP FOREIGN KEY `fk_daytelec_stock_649cd6b6`;
        ALTER TABLE `candletransportequip` DROP FOREIGN KEY `fk_candletr_stock_638921eb`;
        ALTER TABLE `candletransportdepot` DROP FOREIGN KEY `fk_candletr_stock_bc9a81c5`;
        ALTER TABLE `daymedicalprecision` DROP FOREIGN KEY `fk_daymedic_stock_d25d4ce0`;
        ALTER TABLE `candlestockindustry` DROP FOREIGN KEY `fk_candlest_stock_0057f2d9`;
        ALTER TABLE `candlemanufacturing` DROP FOREIGN KEY `fk_candlema_stock_cebe2215`;
        ALTER TABLE `candledistribution` DROP FOREIGN KEY `fk_candledi_stock_dd3cfb17`;
        ALTER TABLE `candleconstruction` DROP FOREIGN KEY `fk_candleco_stock_261c1847`;
        ALTER TABLE `daytransportequip` DROP FOREIGN KEY `fk_daytrans_stock_6abbfb86`;
        ALTER TABLE `daytransportdepot` DROP FOREIGN KEY `fk_daytrans_stock_c3d3ce3f`;
        ALTER TABLE `candleagriculture` DROP FOREIGN KEY `fk_candleag_stock_9242b727`;
        ALTER TABLE `daystockindustry` DROP FOREIGN KEY `fk_daystock_stock_53290646`;
        ALTER TABLE `daymanufacturing` DROP FOREIGN KEY `fk_daymanuf_stock_44bf8ab5`;
        ALTER TABLE `candlemedication` DROP FOREIGN KEY `fk_candleme_stock_6712d14b`;
        ALTER TABLE `candleelectronic` DROP FOREIGN KEY `fk_candleel_stock_d84727ef`;
        ALTER TABLE `daydistribution` DROP FOREIGN KEY `fk_daydistr_stock_e5a80b4d`;
        ALTER TABLE `dayconstruction` DROP FOREIGN KEY `fk_dayconst_stock_c1ba0548`;
        ALTER TABLE `candleinsurance` DROP FOREIGN KEY `fk_candlein_stock_aa22c97d`;
        ALTER TABLE `candlechemistry` DROP FOREIGN KEY `fk_candlech_stock_2105e37b`;
        ALTER TABLE `dayagriculture` DROP FOREIGN KEY `fk_dayagric_stock_16badcd0`;
        ALTER TABLE `candlenonmetal` DROP FOREIGN KEY `fk_candleno_stock_347bcf6a`;
        ALTER TABLE `candlemechanic` DROP FOREIGN KEY `fk_candleme_stock_ef0530eb`;
        ALTER TABLE `daymedication` DROP FOREIGN KEY `fk_daymedic_stock_3993e2c1`;
        ALTER TABLE `dayelectronic` DROP FOREIGN KEY `fk_dayelect_stock_15bbce74`;
        ALTER TABLE `candleservice` DROP FOREIGN KEY `fk_candlese_stock_f4567335`;
        ALTER TABLE `candlefinance` DROP FOREIGN KEY `fk_candlefi_stock_7bc3f306`;
        ALTER TABLE `candleelecgas` DROP FOREIGN KEY `fk_candleel_stock_cefb0964`;
        ALTER TABLE `dayinsurance` DROP FOREIGN KEY `fk_dayinsur_stock_d73c97cd`;
        ALTER TABLE `daychemistry` DROP FOREIGN KEY `fk_daychemi_stock_93518ce7`;
        ALTER TABLE `daynonmetal` DROP FOREIGN KEY `fk_daynonme_stock_f38c012f`;
        ALTER TABLE `daymechanic` DROP FOREIGN KEY `fk_daymecha_stock_29c92e9e`;
        ALTER TABLE `candlesteel` DROP FOREIGN KEY `fk_candlest_stock_0e497b2a`;
        ALTER TABLE `candlefiber` DROP FOREIGN KEY `fk_candlefi_stock_1bd36ef7`;
        ALTER TABLE `dayservice` DROP FOREIGN KEY `fk_dayservi_stock_fe57b0b7`;
        ALTER TABLE `dayfinance` DROP FOREIGN KEY `fk_dayfinan_stock_3f442b61`;
        ALTER TABLE `dayelecgas` DROP FOREIGN KEY `fk_dayelecg_stock_a39fe741`;
        ALTER TABLE `candlewood` DROP FOREIGN KEY `fk_candlewo_stock_aa47ca4e`;
        ALTER TABLE `candlefood` DROP FOREIGN KEY `fk_candlefo_stock_298943d5`;
        ALTER TABLE `candlebank` DROP FOREIGN KEY `fk_candleba_stock_a135f1ef`;
        ALTER TABLE `daysteel` DROP FOREIGN KEY `fk_daysteel_stock_5104b545`;
        ALTER TABLE `dayfiber` DROP FOREIGN KEY `fk_dayfiber_stock_87d3bdc1`;
        ALTER TABLE `keyword` DROP FOREIGN KEY `fk_keyword_stock_971fe9fc`;
        ALTER TABLE `daywood` DROP FOREIGN KEY `fk_daywood_stock_cc7dcb08`;
        ALTER TABLE `dayfood` DROP FOREIGN KEY `fk_dayfood_stock_2c7c8e0e`;
        ALTER TABLE `daybank` DROP FOREIGN KEY `fk_daybank_stock_380418d2`;
        ALTER TABLE `candle` DROP FOREIGN KEY `fk_candle_stock_7013df5a`;
        ALTER TABLE `bidask` DROP FOREIGN KEY `fk_bidask_stock_7d55ead2`;
        ALTER TABLE `day` DROP FOREIGN KEY `fk_day_stock_b8a3096c`;
        ALTER TABLE `day` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `bidask` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candle` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daybank` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayfood` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daywood` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `keyword` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayfiber` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daysteel` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlebank` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlefood` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlewood` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayelecgas` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayfinance` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayservice` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlefiber` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlesteel` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daymechanic` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daynonmetal` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daychemistry` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayinsurance` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleelecgas` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlefinance` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleservice` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayelectronic` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daymedication` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlemechanic` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlenonmetal` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayagriculture` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlechemistry` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleinsurance` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `dayconstruction` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daydistribution` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleelectronic` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlemedication` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daymanufacturing` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daystockindustry` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleagriculture` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daytransportdepot` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daytransportequip` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candleconstruction` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candledistribution` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlemanufacturing` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlestockindustry` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daymedicalprecision` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candletransportdepot` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candletransportequip` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `daytelecommunication` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candlemedicalprecision` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `candletelecommunication` RENAME COLUMN `stock_id` TO `stock_id_id`;
        ALTER TABLE `day` ADD CONSTRAINT `fk_day_stock_24f485b8` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `bidask` ADD CONSTRAINT `fk_bidask_stock_acdf070b` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candle` ADD CONSTRAINT `fk_candle_stock_cc0b126d` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daybank` ADD CONSTRAINT `fk_daybank_stock_c40d00ec` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfood` ADD CONSTRAINT `fk_dayfood_stock_2e44b0e3` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daywood` ADD CONSTRAINT `fk_daywood_stock_8d0f9118` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `keyword` ADD CONSTRAINT `fk_keyword_stock_2dc8f0fe` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfiber` ADD CONSTRAINT `fk_dayfiber_stock_874d5549` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daysteel` ADD CONSTRAINT `fk_daysteel_stock_7bd33878` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlebank` ADD CONSTRAINT `fk_candleba_stock_b98dfc39` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefood` ADD CONSTRAINT `fk_candlefo_stock_7a5a724a` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlewood` ADD CONSTRAINT `fk_candlewo_stock_e0b7b11b` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayelecgas` ADD CONSTRAINT `fk_dayelecg_stock_b6c99500` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayfinance` ADD CONSTRAINT `fk_dayfinan_stock_1a9b39b4` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayservice` ADD CONSTRAINT `fk_dayservi_stock_56088eb4` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefiber` ADD CONSTRAINT `fk_candlefi_stock_2f21b049` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlesteel` ADD CONSTRAINT `fk_candlest_stock_45074222` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymechanic` ADD CONSTRAINT `fk_daymecha_stock_ece1dd8c` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daynonmetal` ADD CONSTRAINT `fk_daynonme_stock_4968b990` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daychemistry` ADD CONSTRAINT `fk_daychemi_stock_a4dfa947` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayinsurance` ADD CONSTRAINT `fk_dayinsur_stock_d2c2c8d7` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleelecgas` ADD CONSTRAINT `fk_candleel_stock_ec339693` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlefinance` ADD CONSTRAINT `fk_candlefi_stock_23d35b23` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleservice` ADD CONSTRAINT `fk_candlese_stock_a1e68575` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayelectronic` ADD CONSTRAINT `fk_dayelect_stock_f9e38102` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymedication` ADD CONSTRAINT `fk_daymedic_stock_3c1751a7` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemechanic` ADD CONSTRAINT `fk_candleme_stock_48933df1` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlenonmetal` ADD CONSTRAINT `fk_candleno_stock_8d21634d` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayagriculture` ADD CONSTRAINT `fk_dayagric_stock_1e97df6d` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlechemistry` ADD CONSTRAINT `fk_candlech_stock_fb7ffa81` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleinsurance` ADD CONSTRAINT `fk_candlein_stock_aa9ab4ee` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `dayconstruction` ADD CONSTRAINT `fk_dayconst_stock_b5bb35af` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daydistribution` ADD CONSTRAINT `fk_daydistr_stock_d1e23d88` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleelectronic` ADD CONSTRAINT `fk_candleel_stock_c0556966` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemedication` ADD CONSTRAINT `fk_candleme_stock_1051af1a` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymanufacturing` ADD CONSTRAINT `fk_daymanuf_stock_7458ffdc` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daystockindustry` ADD CONSTRAINT `fk_daystock_stock_32421c39` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleagriculture` ADD CONSTRAINT `fk_candleag_stock_36e46d3f` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytransportdepot` ADD CONSTRAINT `fk_daytrans_stock_14c727fa` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytransportequip` ADD CONSTRAINT `fk_daytrans_stock_eeada6d9` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candleconstruction` ADD CONSTRAINT `fk_candleco_stock_9754b5a9` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candledistribution` ADD CONSTRAINT `fk_candledi_stock_501160d9` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemanufacturing` ADD CONSTRAINT `fk_candlema_stock_e508eb82` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlestockindustry` ADD CONSTRAINT `fk_candlest_stock_f3a5b062` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daymedicalprecision` ADD CONSTRAINT `fk_daymedic_stock_c2fd76dc` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletransportdepot` ADD CONSTRAINT `fk_candletr_stock_d33969e6` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletransportequip` ADD CONSTRAINT `fk_candletr_stock_210f970a` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `daytelecommunication` ADD CONSTRAINT `fk_daytelec_stock_e633aff5` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candlemedicalprecision` ADD CONSTRAINT `fk_candleme_stock_7db38f8c` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;
        ALTER TABLE `candletelecommunication` ADD CONSTRAINT `fk_candlete_stock_11158675` FOREIGN KEY (`stock_id_id`) REFERENCES `stock` (`id`) ON DELETE CASCADE;"""
