from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `candle` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candle` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candle` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candle` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candle` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `day` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `day` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `day` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daybank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daybank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daybank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATE NOT NULL;
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATE NOT NULL;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `day` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `day` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `day` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candle` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candle` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candle` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candle` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candle` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daybank` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daybank` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daybank` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daywood` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfiber` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daysteel` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlebank` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlewood` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayelecgas` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayfinance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayservice` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefiber` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlesteel` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymechanic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daynonmetal` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daychemistry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayinsurance` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelecgas` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlefinance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleservice` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayelectronic` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymedication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemechanic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlenonmetal` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayagriculture` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlechemistry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleinsurance` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `dayconstruction` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daydistribution` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleelectronic` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymanufacturing` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daystockindustry` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleagriculture` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytransportdepot` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytransportequip` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candleconstruction` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candledistribution` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemanufacturing` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlestockindustry` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daymedicalprecision` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportdepot` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletransportequip` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `daytelecommunication` MODIFY COLUMN `date` VARCHAR(24) NOT NULL;
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candlemedicalprecision` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
        ALTER TABLE `candletelecommunication` MODIFY COLUMN `date` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);"""
